project:
  type: website
  output-dir: _site

website:
  title: "Cedric Martin"
  navbar:
    background: light
    foreground: dark
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: coursework.qmd
        text: Coursework
      - href: about.qmd
        text: About
      - href: resume.qmd
        text: Resume
  page-footer:
    left: "© 2026 Cedric Martin"
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme:
      light: cosmo
    css: styles.css
    toc: false
    smooth-scroll: true
    link-external-newwindow: true
    anchor-sections: true
